language: php
php:
  - '7.0'
  - hhvm
  - nightly

before_script:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpspec run -v --format=pretty
